
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: package.json
    
    - name: Validate Netlify credentials
      run: |
        if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
          echo "ERROR: NETLIFY_AUTH_TOKEN is not set in repository secrets"
          echo "Please add your Netlify Personal Access Token to repository secrets"
          exit 1
        fi
        if [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then
          echo "ERROR: NETLIFY_SITE_ID is not set in repository secrets"
          echo "Please add your Netlify Site ID to repository secrets"
          exit 1
        fi
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Run tests
      run: |
        npm test -- --passWithNoTests --watchAll=false
    
    - name: Build application
      run: |
        npm run build
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: ./build
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 10
